package cn.et.student.entity;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.EMP.EID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.EMP.ENAME
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.EMP.DEPTID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    private Integer deptid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.EMP.EID
     *
     * @return the value of SCOTT.EMP.EID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.EMP.EID
     *
     * @param eid the value for SCOTT.EMP.EID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.EMP.ENAME
     *
     * @return the value of SCOTT.EMP.ENAME
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.EMP.ENAME
     *
     * @param ename the value for SCOTT.EMP.ENAME
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.EMP.DEPTID
     *
     * @return the value of SCOTT.EMP.DEPTID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.EMP.DEPTID
     *
     * @param deptid the value for SCOTT.EMP.DEPTID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }
}