package cn.et.student.entity;


public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.STUDENT.SID
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.STUDENT.SNAME
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.STUDENT.GID
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.STUDENT.AGE
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.STUDENT.SEX
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    private Integer sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.STUDENT.SID
     *
     * @return the value of SCOTT.STUDENT.SID
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.STUDENT.SID
     *
     * @param sid the value for SCOTT.STUDENT.SID
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.STUDENT.SNAME
     *
     * @return the value of SCOTT.STUDENT.SNAME
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.STUDENT.SNAME
     *
     * @param sname the value for SCOTT.STUDENT.SNAME
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.STUDENT.GID
     *
     * @return the value of SCOTT.STUDENT.GID
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.STUDENT.GID
     *
     * @param gid the value for SCOTT.STUDENT.GID
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.STUDENT.AGE
     *
     * @return the value of SCOTT.STUDENT.AGE
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.STUDENT.AGE
     *
     * @param age the value for SCOTT.STUDENT.AGE
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.STUDENT.SEX
     *
     * @return the value of SCOTT.STUDENT.SEX
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.STUDENT.SEX
     *
     * @param sex the value for SCOTT.STUDENT.SEX
     *
     * @mbg.generated Sat Dec 09 09:49:31 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }
}