package cn.et.student.dao;

import cn.et.student.entity.Dept;
import cn.et.student.entity.DeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @SelectProvider(type=DeptSqlProvider.class, method="countByExample")
    long countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @DeleteProvider(type=DeptSqlProvider.class, method="deleteByExample")
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @Delete({
        "delete from SCOTT.DEPT",
        "where DEPTID = #{deptid,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Integer deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @Insert({
        "insert into SCOTT.DEPT (DEPTID, DNAME, ",
        "PID)",
        "values (#{deptid,jdbcType=DECIMAL}, #{dname,jdbcType=VARCHAR}, ",
        "#{pid,jdbcType=DECIMAL})"
    })
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @InsertProvider(type=DeptSqlProvider.class, method="insertSelective")
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @SelectProvider(type=DeptSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="DEPTID", property="deptid", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="DNAME", property="dname", jdbcType=JdbcType.VARCHAR),
        @Result(column="PID", property="pid", jdbcType=JdbcType.DECIMAL)
    })
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @Select({
        "select",
        "DEPTID, DNAME, PID",
        "from SCOTT.DEPT",
        "where DEPTID = #{deptid,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="DEPTID", property="deptid", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="DNAME", property="dname", jdbcType=JdbcType.VARCHAR),
        @Result(column="PID", property="pid", jdbcType=JdbcType.DECIMAL)
    })
    Dept selectByPrimaryKey(Integer deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @UpdateProvider(type=DeptSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @UpdateProvider(type=DeptSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @UpdateProvider(type=DeptSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @Update({
        "update SCOTT.DEPT",
        "set DNAME = #{dname,jdbcType=VARCHAR},",
          "PID = #{pid,jdbcType=DECIMAL}",
        "where DEPTID = #{deptid,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Dept record);
}