package cn.et.student.dao;

import cn.et.student.entity.Emp;
import cn.et.student.entity.EmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @SelectProvider(type=EmpSqlProvider.class, method="countByExample")
    long countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @DeleteProvider(type=EmpSqlProvider.class, method="deleteByExample")
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @Delete({
        "delete from SCOTT.EMP",
        "where EID = #{eid,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @Insert({
        "insert into SCOTT.EMP (EID, ENAME, ",
        "DEPTID)",
        "values (#{eid,jdbcType=DECIMAL}, #{ename,jdbcType=VARCHAR}, ",
        "#{deptid,jdbcType=DECIMAL})"
    })
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @InsertProvider(type=EmpSqlProvider.class, method="insertSelective")
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @SelectProvider(type=EmpSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="EID", property="eid", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ENAME", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEPTID", property="deptid", jdbcType=JdbcType.DECIMAL)
    })
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @Select({
        "select",
        "EID, ENAME, DEPTID",
        "from SCOTT.EMP",
        "where EID = #{eid,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="EID", property="eid", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ENAME", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEPTID", property="deptid", jdbcType=JdbcType.DECIMAL)
    })
    Emp selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @UpdateProvider(type=EmpSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @UpdateProvider(type=EmpSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @UpdateProvider(type=EmpSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    @Update({
        "update SCOTT.EMP",
        "set ENAME = #{ename,jdbcType=VARCHAR},",
          "DEPTID = #{deptid,jdbcType=DECIMAL}",
        "where EID = #{eid,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Emp record);
}