package cn.et.student.entity;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.DEPT.DEPTID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    private Integer deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.DEPT.DNAME
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.DEPT.PID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.DEPT.DEPTID
     *
     * @return the value of SCOTT.DEPT.DEPTID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.DEPT.DEPTID
     *
     * @param deptid the value for SCOTT.DEPT.DEPTID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.DEPT.DNAME
     *
     * @return the value of SCOTT.DEPT.DNAME
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.DEPT.DNAME
     *
     * @param dname the value for SCOTT.DEPT.DNAME
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.DEPT.PID
     *
     * @return the value of SCOTT.DEPT.PID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.DEPT.PID
     *
     * @param pid the value for SCOTT.DEPT.PID
     *
     * @mbg.generated Thu Dec 14 09:01:51 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}